import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext(null);

export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    users: "Users",
    branches: "Branches",
    medicines: "Medicines",
    categories: "Categories",
    batches: "Medicine Batches",
    suppliers: "Suppliers",
    purchases: "Purchases",
    sales: "Sales & Billing",
    prescriptions: "Prescriptions",
    customers: "Customers",
    reservations: "Reservations",
    availability: "Medicine Availability",
    partners: "Partner Medical Shops",
    reports: "Reports",
    notifications: "Notifications",
    settings: "Settings",
    apiAccess: "API Access",
    adminConsole: "System Administrator Console",
    quickDemoLogin: "EVALUATOR QUICK LOGIN (5+ USERS)",
    signInWorkspace: "Sign in to your workspace",
    enterCredentials: "Enter your credentials or choose a verified test account below.",
    continueGoogle: "Continue with Google",
    continueGithub: "Continue with GitHub",
    recentItems: "Recently Accessed",
    noRecent: "No recently accessed records yet",
    searchPlaceholder: "Search medicines, customers, bills, batches...",
    allBranches: "All Branches",
    totalSales: "Total Sales",
    grossProfit: "Gross Profit",
    activeBatches: "Active Batches",
    lowStock: "Low Stock Items",
    nearExpiry: "Expiring Soon",
    expired: "Expired",
    pendingReservations: "Pending Reservations",
    drugInteractionEngine: "Clinical Drug-Drug Interaction Safety Engine",
    checkSafety: "Check Drug Compatibility",
    medibotTitle: "MediBot AI Assistant",
    medibotSubtitle: "Clinical Pharmacy & Stock Assistant",
    askQuestion: "Ask a question about medicines, stock, interaction...",
    logout: "Logout",
    clearRecent: "Clear Recent",
    copyApiKey: "Copy API Key",
    viewAllNotifications: "View all notifications",
    markAllRead: "Mark all read",
    activeStatus: "Active",
    inactiveStatus: "Inactive",
  },
  ta: {
    dashboard: "டாஷ்போர்டு",
    users: "பயனர்கள்",
    branches: "கிளைகள்",
    medicines: "மருந்துகள்",
    categories: "வகைகள்",
    batches: "மருந்து தொகுப்புகள்",
    suppliers: "வழங்குநர்கள்",
    purchases: "கொள்முதல்கள்",
    sales: "விற்பனை & பில்லிங்",
    prescriptions: "மருத்துவர் சீட்டுகள்",
    customers: "வாடிக்கையாளர்கள்",
    reservations: "முன்பதிவுகள்",
    availability: "மருந்து இருப்பு விபரம்",
    partners: "கூட்டு மருந்தகங்கள்",
    reports: "அறிக்கைகள்",
    notifications: "அறிவிப்புகள்",
    settings: "அமைப்புகள்",
    apiAccess: "ஏபிஐ அணுகல் (API)",
    adminConsole: "நிர்வாகி கன்சோல் (Admin)",
    quickDemoLogin: "சோதனை கணக்குகள் (5+ பயனர்கள்)",
    signInWorkspace: "உங்கள் கணக்கில் உள்நுழையவும்",
    enterCredentials: "உங்கள் சான்றுகளை உள்ளிடவும் அல்லது சோதனை கணக்கை தேர்வு செய்யவும்.",
    continueGoogle: "Google மூலம் உள்நுழைக",
    continueGithub: "GitHub மூலம் உள்நுழைக",
    recentItems: "சமீபத்தில் பார்த்தவை",
    noRecent: "சமீபத்திய பதிவுகள் எதுவும் இல்லை",
    searchPlaceholder: "மருந்துகள், பில்கள், தொகுப்புகளைத் தேட...",
    allBranches: "அனைத்து கிளைகள்",
    totalSales: "மொத்த விற்பனை",
    grossProfit: "மொத்த லாபம்",
    activeBatches: "செயலில் உள்ள தொகுப்புகள்",
    lowStock: "குறைந்த இருப்பு",
    nearExpiry: "விரைவில் காலாவதியாகும்",
    expired: "காலாவதியானது",
    pendingReservations: "நிலுவையிலுள்ள முன்பதிவுகள்",
    drugInteractionEngine: "மருந்து ஊடாடல் பாதுகாப்பு அமைப்பு (DDI)",
    checkSafety: "மருந்து பொருந்தக்கூடிய தன்மையை சரிபார்க்கவும்",
    medibotTitle: "மெடிபாட் AI உதவியாளர்",
    medibotSubtitle: "மருத்துவமனை & மருந்து இருப்பு AI",
    askQuestion: "மருந்துகள், இருப்பு பற்றி கேளுங்கள்...",
    logout: "வெளியேறு",
    clearRecent: "அனைத்தையும் நீக்கு",
    copyApiKey: "API சாவியை நகலெடு",
    viewAllNotifications: "அனைத்து அறிவிப்புகள்",
    markAllRead: "அனைத்தும் படித்ததாக குறிக்கவும்",
    activeStatus: "செயலில்",
    inactiveStatus: "செயலற்றது",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    users: "उपयोगकर्ता",
    branches: "शाखाएं",
    medicines: "दवाइयां",
    categories: "श्रेणियां",
    batches: "दवा बैच",
    suppliers: "आपूर्तिकर्ता",
    purchases: "खरीद",
    sales: "बिक्री और बिलिंग",
    prescriptions: "पर्चे (Prescriptions)",
    customers: "ग्राहक",
    reservations: "आरक्षण",
    availability: "दवा उपलब्धता",
    partners: "पार्टनर मेडिकल शॉप्स",
    reports: "रिपोर्ट्स",
    notifications: "सूचनाएं",
    settings: "सेटिंग्स",
    apiAccess: "एपीआई एक्सेस",
    adminConsole: "सिस्टम एडमिनिस्ट्रेटर कंसोल",
    quickDemoLogin: "परीक्षण लॉगिन (5+ खाते)",
    signInWorkspace: "वर्कस्पेस में साइन इन करें",
    enterCredentials: "अपने क्रेडेंशियल दर्ज करें या नीचे एक सत्यापित खाता चुनें।",
    continueGoogle: "Google के साथ जारी रखें",
    continueGithub: "GitHub के साथ जारी रखें",
    recentItems: "हाल ही में देखे गए",
    noRecent: "कोई हालिया रिकॉर्ड नहीं",
    searchPlaceholder: "दवाइयां, ग्राहक, बिल खोजें...",
    allBranches: "सभी शाखाएं",
    totalSales: "कुल बिक्री",
    grossProfit: "सकल लाभ",
    activeBatches: "सक्रिय बैच",
    lowStock: "कम स्टॉक",
    nearExpiry: "शीघ्र समाप्त होने वाला",
    expired: "समाप्त (Expired)",
    pendingReservations: "लंबित आरक्षण",
    drugInteractionEngine: "क्लिनिकल ड्रग इंटरैक्शन सुरक्षा इंजन",
    checkSafety: "दवा अनुकूलता जांचें",
    medibotTitle: "मेडीबॉट एआई सहायक",
    medibotSubtitle: "क्लिनिकल फार्मेसी एवं स्टॉक असिस्टेंट",
    askQuestion: "दवाओं, स्टॉक, इंटरैक्शन के बारे में पूछें...",
    logout: "लॉग आउट",
    clearRecent: "हालिया साफ़ करें",
    copyApiKey: "API कुंजी कॉपी करें",
    viewAllNotifications: "सभी सूचनाएं देखें",
    markAllRead: "सभी पढ़े हुए चिह्नित करें",
    activeStatus: "सक्रिय",
    inactiveStatus: "निष्क्रिय",
  },
  es: {
    dashboard: "Panel de Control",
    users: "Usuarios",
    branches: "Sucursales",
    medicines: "Medicamentos",
    categories: "Categorías",
    batches: "Lotes de Medicamentos",
    suppliers: "Proveedores",
    purchases: "Compras",
    sales: "Ventas y Facturación",
    prescriptions: "Recetas Médicas",
    customers: "Clientes",
    reservations: "Reservas",
    availability: "Disponibilidad",
    partners: "Farmacias Asociadas",
    reports: "Informes",
    notifications: "Notificaciones",
    settings: "Configuración",
    apiAccess: "Acceso API",
    adminConsole: "Consola de Administrador",
    quickDemoLogin: "LOGIN DE PRUEBA (5+ USUARIOS)",
    signInWorkspace: "Inicie sesión en su espacio",
    enterCredentials: "Ingrese sus credenciales o seleccione una cuenta verificada.",
    continueGoogle: "Continuar con Google",
    continueGithub: "Continuar con GitHub",
    recentItems: "Vistos Recientemente",
    noRecent: "No hay registros recientes aún",
    searchPlaceholder: "Buscar medicamentos, clientes, facturas...",
    allBranches: "Todas las Sucursales",
    totalSales: "Ventas Totales",
    grossProfit: "Beneficio Bruto",
    activeBatches: "Lotes Activos",
    lowStock: "Bajo Stock",
    nearExpiry: "Por Vencer",
    expired: "Vencido",
    pendingReservations: "Reservas Pendientes",
    drugInteractionEngine: "Motor de Seguridad de Interacción Farmacológica",
    checkSafety: "Verificar Compatibilidad",
    medibotTitle: "Asistente AI MediBot",
    medibotSubtitle: "Asistente Clínico y de Inventario",
    askQuestion: "Pregunte sobre medicamentos, stock...",
    logout: "Cerrar Sesión",
    clearRecent: "Borrar Recientes",
    copyApiKey: "Copiar Clave API",
    viewAllNotifications: "Ver todas las notificaciones",
    markAllRead: "Marcar todas como leídas",
    activeStatus: "Activo",
    inactiveStatus: "Inactivo",
  },
};

export const LANGUAGES = [
  { code: "en", label: "English", flag: "🇺🇸", short: "EN" },
  { code: "ta", label: "தமிழ்", flag: "🇮🇳", short: "தமிழ்" },
  { code: "hi", label: "हिंदी", flag: "🇮🇳", short: "हिंदी" },
  { code: "es", label: "Español", flag: "🇪🇸", short: "ES" },
];

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    return localStorage.getItem("medilink.lang") || "en";
  });

  const setLang = (code) => {
    setLangState(code);
    localStorage.setItem("medilink.lang", code);
  };

  const t = (key, fallback = "") => {
    const dict = TRANSLATIONS[lang] || TRANSLATIONS.en;
    return dict[key] || TRANSLATIONS.en[key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    return {
      lang: "en",
      setLang: () => {},
      t: (k, fb) => fb || k,
      languages: LANGUAGES,
    };
  }
  return ctx;
}
